[server]

# Максимальный размер загружаемого файла в MB
maxUploadSize = 500

# Запуск Streamlit без открытия браузера внутри контейнера
headless = true

# Отключаем CORS для локального запуска через docker-compose
enableCORS = false

# Отключаем XSRF-защиту для учебного локального стенда
enableXsrfProtection = false